In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('Iris_data_sample - Iris_data_sample.csv',na_values=['??','###'])
df.head()




Unnamed: 0  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0           1            5.1           3.5            1.4           0.2   
1           2            4.9           NaN            1.4           0.2   
2           3            4.7           3.2            1.3           0.2   
3           4            NaN           3.1            1.5           0.2   
4           5            5.0           3.6            NaN           0.2   

       Species  
0  Iris-setosa  
1          NaN  
2  Iris-setosa  
3  Iris-setosa  
4  Iris-setosa

In [43]:
df.isnull().sum()

Unnamed: 0       0
SepalLengthCm    1
SepalWidthCm     1
PetalLengthCm    2
PetalWidthCm     0
Species          1
dtype: int64

In [44]:
df.dropna(axis=0,inplace = True)

In [45]:
df.isnull().sum()

Unnamed: 0       0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [46]:
x = df.iloc[:,1:4]
y = df.iloc[:,-1]


In [47]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=42)


In [48]:
from sklearn.neighbors import KNeighborsClassifier
classifier =  KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)
prediction = classifier.predict(x_test)



In [49]:
from sklearn.metrics import accuracy_score , confusion_matrix
print(accuracy_score(prediction,y_test))

0.8979591836734694


In [50]:
print(confusion_matrix(prediction,y_test))

[[19  0  0]
 [ 0 10  4]
 [ 0  1 15]]


In [52]:
m = []
for i in range(1,20):
    classifier =  KNeighborsClassifier(n_neighbors=i)
    classifier.fit(x_train,y_train)
    prediction = classifier.predict(x_test)
    m.append((prediction!=y_test).sum())
print(m)


[5, 8, 5, 5, 5, 6, 6, 5, 5, 5, 4, 5, 4, 4, 4, 5, 4, 5, 4]
